requires 'Moose';
requires 'Moose::Role';
requires 'namespace::autoclean';
requires 'Readonly';
requires 'Carp';
requires 'FindBin::libs';
requires 'Import::Into';
requires 'Class::Load';
requires 'Try::Tiny';
